# El tiempo en Alicante desde 1 enero 1970 hasta 31 diciembre 2022

In [15]:
pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-12.0.0-cp39-cp39-win_amd64.whl (21.5 MB)
     ---------------------------------------- 21.5/21.5 MB 7.1 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.16.6 in c:\aaa\lib\site-packages (from pyarrow) (1.20.3)
Installing collected packages: pyarrow
Successfully installed pyarrow-12.0.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [2]:
# lista de archivos JSON
archivos_json = ['1970-1975_alicante_alicante.json', '1975-1980_alicante_alicante.json', '1980-1985_alicante_alicante.json',
                             '1985-1990_alicante_alicante.json', '1990-1995_alicante_alicante.json', '1995-2000_alicante_alicante.json',
                             '2000-2005_alicante_alicante.json', '2005-2010_alicante_alicante.json', '2010-2015_alicante_alicante.json', 
                             '2015-2020_alicante_alicante.json', '2020-2023_alicante_alicante.json']

In [3]:
# lista para almacenar los DataFrames de 5 a√±os
dataframes = []

# leer y convertir los archivos JSON en DataFrames
for archivo in archivos_json:
    df = pd.read_json(archivo)
    dataframes.append(df)

# Combinar los DataFrames en el orden deseado
combined_df = pd.concat(dataframes, ignore_index=True)

In [4]:
# formato de fecha 
combined_df['fecha'] = pd.to_datetime(combined_df.fecha, format='%Y-%m-%d')
combined_df['horatmin'] = pd.to_datetime(combined_df.horatmin, format='%H:%M', errors='coerce').dt.time
combined_df['horatmax'] = pd.to_datetime(combined_df.horatmax, format='%H:%M', errors='coerce').dt.time
combined_df['horaracha'] = pd.to_datetime(combined_df.horaracha, format='%H:%M', errors='coerce').dt.time
combined_df['horaPresMax'] = pd.to_datetime(combined_df.horaPresMax, format='%H', errors='coerce').dt.time
combined_df['horaPresMin'] = pd.to_datetime(combined_df.horaPresMin, format='%H', errors='coerce').dt.time

In [5]:
combined_df = combined_df.replace(',', '.', regex=True)

In [7]:
combined_df.prec = combined_df.prec.replace('Ip', '0.0', regex=True)

In [11]:
combined_df

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,horatmin,tmax,horatmax,dir,velmedia,racha,horaracha,sol,presMax,horaPresMax,presMin,horaPresMin
0,1970-01-01,8025,ALACANT/ALICANTE,ALICANTE,81,9.3,0.0,5.0,01:15:00,13.6,14:20:00,32.0,3.1,11.1,13:06:00,6.4,1000.6,NaT,993.0,00:00:00
1,1970-01-02,8025,ALACANT/ALICANTE,ALICANTE,81,7.0,7.8,3.6,05:45:00,10.4,12:30:00,5.0,2.2,4.7,16:07:00,0.0,1001.0,10:00:00,998.1,19:00:00
2,1970-01-03,8025,ALACANT/ALICANTE,ALICANTE,81,11.1,0.0,7.4,00:45:00,14.8,15:20:00,23.0,1.4,5.0,14:14:00,3.5,998.2,00:00:00,995.4,NaT
3,1970-01-04,8025,ALACANT/ALICANTE,ALICANTE,81,13.8,0.2,9.0,05:20:00,18.6,15:15:00,27.0,0.6,6.4,22:20:00,1.8,995.4,00:00:00,989.3,15:00:00
4,1970-01-05,8025,ALACANT/ALICANTE,ALICANTE,81,14.6,0.5,9.8,05:30:00,19.4,14:20:00,23.0,0.8,7.2,00:14:00,6.4,991.4,10:00:00,988.8,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19353,2022-12-27,8025,ALACANT/ALICANTE,ALICANTE,81,13.3,0.0,6.6,07:00:00,20.0,13:30:00,14.0,1.1,4.4,14:20:00,8.9,1021.5,11:00:00,1018.5,01:00:00
19354,2022-12-28,8025,ALACANT/ALICANTE,ALICANTE,81,12.7,0.0,6.1,04:30:00,19.3,13:20:00,14.0,0.6,3.9,14:10:00,8.6,1019.1,00:00:00,1013.8,NaT
19355,2022-12-29,8025,ALACANT/ALICANTE,ALICANTE,81,14.2,0.0,6.6,02:10:00,21.9,13:00:00,23.0,1.4,7.2,12:10:00,8.2,1015.0,10:00:00,1012.7,14:00:00
19356,2022-12-30,8025,ALACANT/ALICANTE,ALICANTE,81,17.2,0.0,10.5,03:50:00,24.0,13:50:00,28.0,2.8,10.3,11:20:00,6.7,1016.4,23:00:00,1013.9,NaT
19357,2022-12-31,8025,ALACANT/ALICANTE,ALICANTE,81,15.0,0.0,8.6,23:50:00,21.3,12:20:00,16.0,1.4,6.4,13:10:00,8.3,1017.5,NaT,1015.4,15:00:00

In [12]:
# guardar todo el dataframe
combined_df.to_parquet('dataframe_1970-2023_alicante_alicante.parquet')